Tirspec H1RG support
indiajoe/HxRGproc pull request #6
Opened 2023-08-06 14:54 UTC by varghesereji

The package HxRGproc can reduce data from the instruments TANSPEC, which have H2RG Detector in spectrograph, and TIRSPEC, which is a spectrograph with H1RG Detector.

2023-08-06 15:09 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +       FrameTime = header['ITIME']  #Time taken for each readout.
I think the header keyword for the NDR readout time is `NDRRDTM`

2023-08-06 15:13 UTC, indiajoe requested changes
Here are some suggestions. I shall add more once I test it on data.

2023-08-06 15:13 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +       time = int(Frame_Number) * FrameTime
Unlike TANSPEC the keyword here does not reset at the beginning of an up the ramp. We should think how to subtract the first number from the up-the-ramp.

2023-08-06 15:13 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +       Frame_Number = re.search('.*(\d+?)\.fits',os.path.basename(fname)).group(1)
You could use the regular expression `'.*debug-(\d+?)\.fits'` instead.

2023-08-06 17:40 UTC, indiajoe requested changes
Some more edit request after testing on TIRSPEC data.

2023-08-06 17:40 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +    return tuple(map(int,re.search('.*-(\d+?)-(\d+?)\.fits',os.path.basename(fname)).group(1,2)))
This Regexp should be `'.*-(\d+?)-debug-(\d+?)\.fits'`

2023-08-06 17:40 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +    'TIRSPEC':{'RampFilenameString':'{0}.',#Input filename structure with Ramp id substitution
It should be a - in the end not . like in TANSPEC. `'RampFilenameString':'{0}-'`

2023-08-06 17:40 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +                   'RampidRegexp':'(.*?-\d*?)-\.\d*\.fits',# Regexp to extract unique Ramp id from filename
This should be `'RampidRegexp':'(.*?-\d*?)-debug-\d*\.fits'`

2023-08-06 17:40 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +    'TIRSPEC':{'RampFilenameString':'-{0}.',#Inpui filename structure with Ramp id substitution
It should be a - in the end not . like in TANSPEC. `'RampFilenameString':'{0}-'`

2023-08-06 17:40 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
>      'SpecTANSPEC':{'RampFilenameString':'-{0}.Z.',#Inpui filename structure with Ramp id substitution
This also should be `'RampFilenameString':'{0}.Z.'` 
No need of - in the beginning.

2023-08-06 17:40 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +                   'RampidRegexp':'.*-(\d*?)-\d*?\.fits',# Regexp to extract unique Ramp id from filename
This should be `'RampidRegexp':'(.*?-\d*?)-debug-\d*\.fits'`

2023-08-06 17:40 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +    """ Function which returns the key to sort SpecTANSPEC filename """
Update docstring SpecTANSPEC -> TIRSPEC

2023-08-07 04:06 UTC, varghesereji commented on HxRGproc/reduction/instruments.py
> +       FrameTime = header['ITIME']  #Time taken for each readout.
You mean replace NDRITIME with NDRRDTM right?

2023-08-07 05:24 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +       FrameTime = header['ITIME']  #Time taken for each readout.
No, replace ITIME with NDRRDTM

2023-08-07 09:10 UTC, indiajoe requested changes

2023-08-07 09:10 UTC, indiajoe commented on HxRGproc/reduction/instruments.py
> +                   'RampidRegexp':'(.*?-\d*?)-\.\d*\.fits',# Regexp to extract unique Ramp id from filename
Is this not updated?

2023-08-07 16:22 UTC, indiajoe approved these changes
Thanks for all the updates

2023-08-07 16:23 UTC, merged